In [96]:
# Import all standard libraries for Practical Linear Algebra
#
# LIBRARIES:
# - numpy (np): Linear algebra operations, arrays, matrices
# - matplotlib.pyplot (plt): Plotting and visualization
# - sympy (sym): Symbolic math, RREF calculations
# - scipy: Scientific computing, LU decomposition
# - pandas (pd): Data handling, DataFrames

import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
import scipy
import pandas as pd
from IPython.display import display, Math

# Question 1

In [98]:
#task 1
print(f"{"\n\n"}\033[1;32m#task 1\033[0m")

v = np.array([3, -6, 2])
w = np.array([0, 4, -1])

v_norm_2 = np.sqrt(np.dot(v, v))

display(Math(r"\|v\|_2 = \sqrt{\sum_x{v_x^2}}"))

v_norm = np.linalg.norm(v, ord=2)  # L2: Euclidean distance

print(f"norm(v) = {v_norm}")



#task 2
print(f"{"\n\n"}\033[1;32m#task 2\033[0m")

v_unit = v/v_norm

display(Math(r"\textbf{Unit Vector:} \quad \hat{v} = \frac{v}{\|v\|}"))

print(f"unit(v) = {v_unit}")



#task 3
print(f"{"\n\n"}\033[1;32m#task 3\033[0m")

display(Math(r"\textbf{Vector Projection:} \quad \mathbf{u}_{\parallel} = \frac{\mathbf{u} \cdot \mathbf{v}}{\mathbf{v} \cdot \mathbf{v}} \mathbf{v}"))

v_onto_w = (np.dot(v, w) / np.dot(w, w)) * w

w_perp = v - v_onto_w

print(f"v projectet onto w = {v_onto_w}")




#task 1


<IPython.core.display.Math object>

norm(v) = 7.0


#task 2


<IPython.core.display.Math object>

unit(v) = [ 0.42857143 -0.85714286  0.28571429]


#task 3


<IPython.core.display.Math object>

v projectet onto w = [-0.         -6.11764706  1.52941176]


# Question 2

In [100]:


#task 1
print(f"{"\n\n"}\033[1;32m#task 1\033[0m")
A = np.array([
    [2, 1, 0, 3],
    [0, 4, 1, 2],
    [1, 0, 3, 1],
    [3, 2, 1, 0],
    [1, 1, 2, 4]
])

print(f"A = \n{A}")

#task 2
print(f"{"\n\n"}\033[1;32m#task 2.1\033[0m")

# calculate A^T A
A_T = A.T

A_T_A = A_T@A

print(f"A^t A = {A_T_A}")

# Calculate trace: sum of diagonal elements
display(Math(r"\textbf{Trace:} \quad \text{tr}(\mathbf{A^t A}) = \sum_{i=1}^{n} a_{ii}"))

A_T_A_trace = np.trace(A_T_A)

print(f"trace(A^t A) = {A_T_A_trace}")


# Frobenius norm
#task 2.2
print(f"{"\n\n"}\033[1;32m#task 2.1\033[0m")

display(Math(r"\textbf{Matrix Rank:} \quad \text{rank}(\mathbf{A}) = \text{number of linearly independent rows/columns}"))

A_T_A_norm_fro = np.linalg.norm(A_T_A, ord='fro')

print(f"fro_norm(A^t A) = {A_T_A_norm_fro}")


#task 3
print(f"{"\n\n"}\033[1;32m#task 3\033[0m")
print(f"\n{'='*50}")
print("The number of linearly independent columns of A can be at most 4, since A has 4 columns (each vector lies in a 5-dimensional space).")
print("There are no obvious linearly dependent columns, which suggests full column rank.")
print(f"If all vectors were linearly dependent, this would lead to the norm and trace being equal, which they are not.")
print("This supports the conclusion that the rank is 4, since there is no evidence of linear dependence.")
print("However, to confirm this, a rank test is preformed.")
print(f"{'='*50}\n")
A_rank = np.linalg.matrix_rank(A)
print(f"A_rank = {A_rank}")  




#task 1
A = 
[[2 1 0 3]
 [0 4 1 2]
 [1 0 3 1]
 [3 2 1 0]
 [1 1 2 4]]


#task 2.1
A^t A = [[15  9  8 11]
 [ 9 22  8 15]
 [ 8  8 15 13]
 [11 15 13 30]]


<IPython.core.display.Math object>

trace(A^t A) = 82


#task 2.1


<IPython.core.display.Math object>

fro_norm(A^t A) = 57.28874234961002


#task 3

The number of linearly independent columns of A can be at most 4, since A has 4 columns (each vector lies in a 5-dimensional space).
There are no obvious linearly dependent columns, which suggests full column rank.
If all vectors were linearly dependent, this would lead to the norm and trace being equal, which they are not.
This supports the conclusion that the rank is 4, since there is no evidence of linear dependence.
However, to confirm this, a rank test is preformed.

A_rank = 4


# Question 3

In [102]:
#task 1
print(f"{"\n\n"}\033[1;32m#task 1\033[0m")

display(Math(r"\textbf{Left Inverse:} \quad \mathbf{A}_{\text{left}}^{-1} = (\mathbf{A}^T \mathbf{A})^{-1} \mathbf{A}^T"))

R = np.linalg.inv(A_T_A) @ A_T

print(R)


#task 2
print(f"{"\n\n"}\033[1;32m#task 2\033[0m")

display(Math(r"\textbf{Property:} \quad \mathbf{A}_{\text{left}}^{-1} @ \mathbf{A} = \mathbf{I}"))

# Verify: should be identity matrix
print(np.round(R @ A, 8))

print("\n The left inverse exists so there is no need to make the right inverse")



#task 1


<IPython.core.display.Math object>

[[ 0.1527913  -0.15197988 -0.00673483  0.24602402 -0.03691983]
 [-0.05241805  0.24066861 -0.06247971  0.07757222 -0.06540084]
 [-0.18313859  0.02815644  0.28635183  0.00941253  0.05168776]
 [ 0.1495456  -0.01014281 -0.05704317 -0.13307368  0.157173  ]]


#task 2


<IPython.core.display.Math object>

[[ 1. -0. -0. -0.]
 [-0.  1. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -0. -0.  1.]]

 The left inverse exists so there is no need to make the right inverse


# Question 4

In [121]:
print(f"{"\n\n"}\033[1;32m#Question 4\033[0m")

display(Math(r"\textbf{System of Linear Equations:} \quad \mathbf{Ax} = \mathbf{b}"))

# 2x + y - z + w = 4
# x - y + 2z + w = 1
# 3x + 2y + z - w = 10
# x + y + z + w = 6

# 2x + 1y − 1z + 1w = 4
# 1x − 1y + 2z + 1w = 1
# 3x + 2y + 1z − 1w = 10
# 1x + 1y + 1z + 1w = 6


A = np.array([
    [2, 1, -1, 1],
    [1, -1, 2, 1],
    [3, 2, 1, -1],
    [1, 1, 1, 1]
])
b = np.array([4, 1, 10, 6])

display(Math(r"\textbf{Augmented Matrix:} \quad [\mathbf{A} | \mathbf{b}]"))

M = np.hstack((A, b.reshape(-1, 1)))

symMat = sym.Matrix(M)
rrefMat, pivotCols = symMat.rref()

print(f"RREF Matrix:\n{rrefMat}")
print(f"Pivot Columns: {pivotCols}")

(x,y,z,w) = rrefMat[:,4]


print(f"x = {x} = {float(x):.4f}")
print(f"y = {y} = {float(y):.4f}")
print(f"z = {z} = {float(z):.4f}")
print(f"w = {w} = {float(w):.4f}")




#Question 4


<IPython.core.display.Math object>

<IPython.core.display.Math object>

RREF Matrix:
Matrix([[1, 0, 0, 0, 20/23], [0, 1, 0, 0, 74/23], [0, 0, 1, 0, 33/23], [0, 0, 0, 1, 11/23]])
Pivot Columns: (0, 1, 2, 3)
x = 20/23 = 0.8696
y = 74/23 = 3.2174
z = 33/23 = 1.4348
w = 11/23 = 0.4783


# Question 5

In [136]:
#task 1
print(f"{"\n\n"}\033[1;32m#task 1\033[0m")

B = np.array([
    [3, 1, 0],
    [0, 3, 0],
    [0, 1, 5]
    ])

display(Math(r"\textbf{Diagonalization:} \quad \mathbf{A} = \mathbf{V} \mathbf{D} \mathbf{V}^{-1}"))


eigenvalues, eigenvectors = np.linalg.eig(B)

V = eigenvectors
D = np.diag(eigenvalues)
V_inv = np.linalg.inv(V)

print(f"V =\n{np.round(V, 2)}")
print(f"D =\n{np.round(D, 2)}")
print(f"V^-1 =\n{np.round(V_inv, 2)}")

print("\n")

print("Rank of eigenvector matrix:", np.linalg.matrix_rank(eigenvectors))
print("Matrix size:", B.shape[0])

print("The eigenvector matrix has rank 2, meaning it contains only 2 linearly independent eigenvectors.")
print("A 3x3 matrix requires 3 linearly independent eigenvectors to be diagonalizable.")
print("Since there are only 2 independent eigenvectors, the matrix is not diagonalizable.")

#task 2
print(f"{"\n\n"}\033[1;32m#task 2\033[0m")

display(Math(r"\textbf{Property:} \quad \mathbf{A}^n = \mathbf{V} \mathbf{D}^n \mathbf{V}^{-1}"))

# Verify: V @ D @ V^-1 should equal B
B_reconstructed = V @ D @ V_inv

print(f"B reconstructed =\n{np.round(B_reconstructed, 2)}")

print(f"Reconstruction correct: {np.allclose(B, B_reconstructed)}")

print(f"The matrix chould not be recunstructed")




#task 1


<IPython.core.display.Math object>

V =
[[ 0.  1. -1.]
 [ 0.  0.  0.]
 [ 1.  0. -0.]]
D =
[[5. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
V^-1 =
[[0.00000000e+00 5.00000000e-01 1.00000000e+00]
 [1.00000000e+00 1.50119988e+15 0.00000000e+00]
 [0.00000000e+00 1.50119988e+15 0.00000000e+00]]


Rank of eigenvector matrix: 2
Matrix size: 3
The eigenvector matrix has rank 2, meaning it contains only 2 linearly independent eigenvectors.
A 3x3 matrix requires 3 linearly independent eigenvectors to be diagonalizable.
Since there are only 2 independent eigenvectors, the matrix is not diagonalizable.


#task 2


<IPython.core.display.Math object>

B reconstructed =
[[3.   0.25 0.  ]
 [0.   3.   0.  ]
 [0.   1.   5.  ]]
Reconstruction correct: False
The matrix chould not be recunstructed


# Question 6

In [139]:
#task 1
print(f"{"\n\n"}\033[1;32m#task 1\033[0m")

display(Math(r"$\mathbf{A} = \mathbf{U} \mathbf{\Sigma} \mathbf{V}^T$"))

U, s, Vt = np.linalg.svd(B)

# Construct Sigma matrix from singular values
Sigma = np.zeros_like(B, dtype=float)
np.fill_diagonal(Sigma, s)

print(f"U:\n{np.round(U, 2)}\n")
print(f"S (singular values):\n{np.round(s, 2)}\n")
print(f"V^T:\n{np.round(Vt, 2)}")



#task 2
print(f"{"\n\n"}\033[1;32m#task 2\033[0m")

# Verify: U @ Sigma @ Vt should equal B
B_reconstructed = U @ Sigma @ Vt

print(f"B reconstructed =\n{np.round(B_reconstructed, 2)}")
print(f"Reconstruction correct: {np.allclose(B, B_reconstructed)}")




#task 1


<IPython.core.display.Math object>

U:
[[ 0.09  0.78  0.61]
 [ 0.18  0.59 -0.78]
 [ 0.98 -0.18  0.09]]

S (singular values):
[5.16 3.47 2.51]

V^T:
[[ 0.05  0.31  0.95]
 [ 0.68  0.69 -0.26]
 [ 0.73 -0.66  0.18]]


#task 2
B reconstructed =
[[ 3.  1. -0.]
 [-0.  3.  0.]
 [ 0.  1.  5.]]
Reconstruction correct: True


# Question 7

In [142]:
X = np.array([
    [3, 8, 68],
    [5, 10, 78],
    [7, 6, 82],
    [6, 12, 90],
    [8, 9, 88],
    [4, 5, 65],
    [9, 11, 95],
    [5, 7, 74]
])


#task 1
print(f"{"\n\n"}\033[1;32m#task 1\033[0m")

# Apply data to named var
hours = X[:,0]
completed = X[:,1]
scores = X[:,2]


# Design matrix: add intercept column
X_design = np.column_stack((np.ones(hours.shape[0]), hours, completed))
y = scores.astype(float)

# Solve least squares: X_design @ beta = y
beta, residuals, rank, svals = np.linalg.lstsq(X_design, y, rcond=None)

beta0, beta1, beta2 = beta
print(f"Model: y = beta0 + beta1*x1 + beta2*x2")
print(f"Model: y = {beta0:.4f} + {beta1:.4f}*x1 + {beta2:.4f}*x2")
print(f"Model: y = {beta0:.4f} + {beta1:.4f}*hours + {beta2:.4f}*completed")



#task 2
print(f"{"\n\n"}\033[1;32m#task 2\033[0m")

# Predict for a new sample
hours_pred = 6
completed_pred = 8.0
y_pred = beta0 + beta1 * hours_pred + beta2 * completed_pred
print(f"Predicted score for hours={hours_pred}, completed={completed_pred}: {y_pred:.4f}")


#task 3
print(f"{"\n\n"}\033[1;32m#task 3\033[0m")
# SSE (Sum of Squared Errors)
display(Math(r"\textbf{SSE:} \quad \mathrm{SSE} = \sum_{i=1}^{m}(y_i - \hat{y}_i)^2"))
y_fitted = X_design @ beta
SSE = np.sum((y - y_fitted) ** 2)
print(f"SSE: {SSE:.4f}")



#task 1
Model: y = beta0 + beta1*x1 + beta2*x2
Model: y = 41.3830 + 3.7726*x1 + 1.9357*x2
Model: y = 41.3830 + 3.7726*hours + 1.9357*completed


#task 2
Predicted score for hours=6, completed=8.0: 79.5037


#task 3


<IPython.core.display.Math object>

SSE: 21.9082


# Question 8

1. The columns of Q form a basis for R^n.  ✅ yes as they are orthogonal that means the basis span the hole space as they are also independent

none of the above 

# Question 9

- 1 ❌ (there is only 3 basis vectors, so these form a 3d space, not 4d)
- 2 ❌ The basis vectors them self can be written as a linear combination of the basis vectors, and they can also create others if they fall inside the subspace
- 3 ❌ Only if the new vector is linear independent form the other basis vectors
- 4 ❌ linear independent $ \ne $ orthogonal. so they can also be just linear independent
- 5 ✅ none of the above is true

# Question 10

the singular values show the importance of each dimension. the dimensions being U and V^T

if the singular value is big for let's say [1] dimension, then this means that a big portion of the data can be explained in this dimension 

and if the singular value is small for let's say [10] dimension, when the singular value is lov then this dominion doesn't explain a lot of the data

U[1] s[1] V_T[1] = explains a lot of the data. where s[1] = big value  
U[10] s[10] V_T[10] = doesn't explain a lot in the data. where s[10] = small value

# Question 11

The column space of A where rows(m) > columns(n) is a subspace of R^m as there is at most n dimensions in this space and as m > n this space always has a lower dimension then m

b is the model that we want to explain the data with and this model doesn't land inside the column space

to fix this problem b is projected onto the column space to find the best possible approximation of the model

this is the core idea in least squares where we want to minimize for error by getting a model that is as close to the column space of A as possible, and this is the projection of b onto the column space of A

