# Lesson 5 - exercises for matrices part 2

# Exercise 1



Construct the 3x3 identity matrix and the 3x3 zero matrix.
Before doing any calculations with python, try to think about what the
norm and the trace of both matrices would be? (write it down!)

Then use python to calcuate both the norm and the trace of these two matrices.
Does the result corresponds with your expectations.

Consider what the rank of these two matrices should be?
Calculate it using python for both of them and see if it corresponds to your expectations.

In [8]:
import numpy as np

identity_matrix = np.eye(3)
zero_matrix = np.zeros((3,3))


print(identity_matrix,"\n")
print(zero_matrix)

print(f"""
Norm:
normen for identity_matrix vil være sqrt af 3 som nok er omkring 1.7
for zero_matrix vil normen være 0

trace:
trace for identity_matrix vil være 3 da det er summen af diagonalen
for zero_matrix vil trace være 0 da alle elementer er 0

Norm:
identity_matrix = {np.linalg.norm(identity_matrix)} 
zero_matrix = {np.linalg.norm(zero_matrix)}

trace:
identity_matrix = {np.trace(identity_matrix)}
zero_matrix = {np.trace(zero_matrix)}

Randk:
Randk for identity_matrix vil være 3 da den indeholder 3 linært uafhængige rækker, svarende til standard basis i R^3
for zero_matrix vil ranken være 0 da der ikke er nogen dimention udspændt af vectorene i matrixen, desse beskriver kun null space

rank:
identity_matrix = {np.linalg.matrix_rank(identity_matrix)}
zero_matrix = {np.linalg.matrix_rank(zero_matrix)}

""")


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Norm:
normen for identity_matrix vil være sqrt af 3 som nok er omkring 1.7
for zero_matrix vil normen være 0

trace:
trace for identity_matrix vil være 3 da det er summen af diagonalen
for zero_matrix vil trace være 0 da alle elementer er 0

Norm:
identity_matrix = 1.7320508075688772 
zero_matrix = 0.0

trace:
identity_matrix = 3.0
zero_matrix = 0.0

Randk:
Randk for identity_matrix vil være 3 da den indeholder 3 linært uafhængige rækker, svarende til standard basis i R^3
for zero_matrix vil ranken være 0 da der ikke er nogen dimention udspændt af vectorene i matrixen, desse beskriver kun null space

rank:
identity_matrix = 3
zero_matrix = 0




# Exercise 2

Construct a 2x2 and a 3x3 and a 4x4 diagonal matrix (i.e. only values on the diagonal - you choose which, but is should not be the identity matrix), the rest is zero in the matrix
Compute the rank of these 3 matrices.
Consider the results, and come up with an argument to why you get these results

In [11]:
def make_side_eye(n):
    side_eye_m = np.zeros((n,n))
    for i in range(n):
        side_eye_m[i,n-1-i] = 1
    return side_eye_m

m_2 = make_side_eye(2)
m_3 = make_side_eye(3)
m_4 = make_side_eye(4)


print(m_2,"\n")
print(m_3,"\n")
print(m_4,"\n")


#Rabk:

print(np.linalg.matrix_rank(m_2),"\n")
print(np.linalg.matrix_rank(m_3),"\n")
print(np.linalg.matrix_rank(m_4),"\n")
    

[[0. 1.]
 [1. 0.]] 

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] 

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

2 

3 

4 



# Exercise 3

1. Calculate the determinants of these 3 matrices from exercise 2.

  Notice, that the results may look at little "weird" due to floating point calculations giving rounding errors, so use round(x) on the result

  Look at the determinant values for each matrix and see if you can come up with a formula for how to calculate the determinat of a diagonal matrix (it's much easier than the general determinant formula!)

2. Find the determinant of M defined below. Give a reason for your result.


In [ ]:
 M = np.array([[1, 0, 0, 0],
              [0, 2, 0, 0],
              [0, 0, 3, 0]])

# Exercise 4

Calculate the norm of the 3 matrices from exercise 3 using python

Try to come up with a general formula for calculating the (Frobenius) norm of a diagonal matrix based on your results

# Exercise 5

Solve exercise 6-5 in the book.



In [ ]:
#hint - in order to create a random matrix with specified dimensions M and r you can do this (define M and r before)

A = np.random.randn(M,r)

# Exercise 6

Solve exercise 6-6 in the book.

Hint: An easy way to create a rank-1 matrix is to create a 1x4 matrix for instance, where all values except 1 is zero.

The trick is to construct the to matrices, A and B in each of the 3 cases, both with rank 1, in a "clever" way, so that the rank of A+B in each instance is rank 0, rank 1 and rank 2.

It's optional if you want to try it out with multiplication instead.

# Exercise 7

Solve exercise 6-8 from the book.
You can try it out with different A matrices to see that it still holds

# Exercise 8

Solve exercise 6-9 from the book

In [ ]:
#hints - you can easily create random matrices and vectors of any size desired

A = np.random.randn(4,3)
v = np.random.randn(4,1)

#In order to check if a vector is part of the column space, we can
#simply "append" the vector v to A, calling this matrix A_V, such that
#A_V contains an extra column with v - in python this can be done like this:

A_V = np.hstack((A,v))

#Now if the ranks of A and A_V are the same, then v is in the column space.
#If they are different, v is not in the column space.

#Why is that the case?
