# Loading libraries needed here


In [1]:
import numpy as np
import matplotlib.pyplot as plt

# used to create non-regular subplots
import matplotlib.gridspec as gridspec

# Exercise 1


Create the QR matrices from a random matrix:

Q,R  = np.linalg.qr( np.random.randn(5,5) )

Then verify in python that the following 4 expressions
give I (we are not using R matrix here):

 Q.T @ Q, \
 Q @ Q.T, \
 inverse Q @ Q, \
  Q @ inverse Q, \
(the formular on page 155 in the book)

In [6]:
Q,R  = np.linalg.qr( np.random.randn(5,5) )
"""
 Q.T @ Q, \
 Q @ Q.T, \
 inverse Q @ Q, \
  Q @ inverse Q, \
"""
print(np.round(Q.T @ Q, 5),"\n")
print(np.round(Q @ Q.T, 5),"\n")
print(np.round(np.linalg.inv(Q) @ Q, 5),"\n")
print(np.round(Q @ np.linalg.inv(Q), 5),"\n")

[[ 1.  0.  0.  0. -0.]
 [ 0.  1.  0. -0.  0.]
 [ 0.  0.  1. -0. -0.]
 [ 0. -0. -0.  1.  0.]
 [-0.  0. -0.  0.  1.]] 

[[ 1. -0. -0. -0.  0.]
 [-0.  1. -0.  0.  0.]
 [-0. -0.  1. -0. -0.]
 [-0.  0. -0.  1.  0.]
 [ 0.  0. -0.  0.  1.]] 

[[ 1.  0.  0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [ 0.  0.  1.  0. -0.]
 [ 0.  0. -0.  1. -0.]
 [ 0.  0. -0. -0.  1.]] 

[[ 1. -0. -0.  0. -0.]
 [-0.  1.  0.  0. -0.]
 [ 0. -0.  1. -0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0. -0.  0. -0.  1.]] 



# Exercise 2

Create a random matrix, U, of dimensions 6,6

Then calculate Q,R of U using QR decomposition.

Then calculate the QR decomposition of the Q matrix from before (in order to not be confused call the new matrices Q2 and R2 as they are not the same as Q and R).

Confirm that R2 is I, the Identity Matrix.

And why is that indeed the case?

In [14]:
u = np.random.randint(low=-10, high=10, size=(6,6))
print(u,"\n")

Q,R = np.linalg.qr(u)

Q2,R2 = np.linalg.qr(Q)

print(np.round(R2,3),"\n")

print("""
Q er ortegonal så for at lave den ortegonale matrix er der ikke brug for R2 da alt informationen kan stå i Q2
""")

print(np.round(Q,3),"\n")

print(np.round(Q2,3),"\n")


[[ -3  -6   2  -8 -10  -2]
 [  6 -10  -7  -2   6  -6]
 [ -4   4  -2   7   5   1]
 [ -2  -2   4   3  -9   5]
 [ -7   7   5  -6  -4   4]
 [  9  -7   6   8  -5  -5]] 

[[ 1.  0. -0.  0.  0. -0.]
 [ 0.  1.  0. -0.  0.  0.]
 [ 0.  0.  1. -0. -0.  0.]
 [ 0.  0.  0.  1. -0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 


Q er ortegonal så for at lave den ortegonale matrix er der ikke brug for R2 da alt informationen kan stå i Q2

[[-0.215 -0.806  0.206  0.14  -0.058  0.489]
 [ 0.43  -0.461 -0.499  0.073 -0.405 -0.43 ]
 [-0.286  0.056 -0.233 -0.77  -0.463  0.231]
 [-0.143 -0.349  0.356 -0.48   0.363 -0.607]
 [-0.501  0.098  0.341  0.343 -0.606 -0.372]
 [ 0.645  0.062  0.641 -0.184 -0.345  0.128]] 

[[-0.215 -0.806  0.206  0.14  -0.058  0.489]
 [ 0.43  -0.461 -0.499  0.073 -0.405 -0.43 ]
 [-0.286  0.056 -0.233 -0.77  -0.463  0.231]
 [-0.143 -0.349  0.356 -0.48   0.363 -0.607]
 [-0.501  0.098  0.341  0.343 -0.606 -0.372]
 [ 0.645  0.062  0.641 -0.184 -0.345  0.128]] 



# Exercise 3

Create 3 random matrices (you can use code like the one from exercise 1 and modify) of size 4x4, 5x5, 6x6.

Make sure they are invertible - for instance by calculating the determinant, if not just run the code again!

For each of the 3 matrices calculate the inverse using the in-built python metod (as you did many times before) and then calculate using QR decomposition (the formular on one of the slides) and finally subtract the two inverses from each other - this should result in the zero-matrix (or close) for all 3 matrices (as the two inverses calculated should be the same theoretically)
Indeed, check that is the case.

It might be difficult to visually inspect a 6x6 matrix, so an easy check is to calculate the norm of the difference of the two inverses - this gives a single number, which should be zero (or very close to zero). Try this in at least one of the 3 cases.


If one of the subtractions between the two inverses are not zero, try to come up with some suggestions for why they are not 100% identical.

In [18]:
"""
Task
1. Create matrices
Generate 3 random matrices:
4×4
5×5
6×6
Ensure each matrix is invertible
Check determinant ≠ 0
If not, generate a new matrix
"""

matrixes = [0,0,0]
while True:
    matrixes[0] = np.random.rand(4,4)
    if np.linalg.det(matrixes[0]) != 0:
        break

while True:
    matrixes[1] = np.random.rand(5,5)
    if np.linalg.det(matrixes[1]) != 0:
        break

while True:
    matrixes[2] = np.random.rand(6,6)
    if np.linalg.det(matrixes[2]) != 0:
        break


"""
2. Compute inverses (2 methods)
For each matrix:
Find inverse using built-in Python method
Find inverse using QR decomposition
"""
inverse_builtin = [np.linalg.inv(matrix) for matrix in matrixes]

inverse_qr = [0,0,0]
for i, matrix in enumerate(matrixes):
    Q,R = np.linalg.qr(matrix)
    inverse_qr[i] = np.linalg.inv(R) @ Q.T

"""
3. Compare results
For each matrix:
Subtract the two inverses
Result should be ≈ zero matrix
"""
diffrence = [0,0,0]
for i in range(3):
    diffrence[i] = inverse_builtin[i] - inverse_qr[i]
    print(f"diffrence for matrix {i}:\n {np.round(diffrence[i], 5)}\n")
"""
4. Verify accuracy
Check that differences are close to zero
For at least one matrix:
Compute the norm of the difference
Should be ≈ 0
"""
norms = [0,0,0]
for i in range(3):
    norms[i] = np.linalg.norm(diffrence[i],ord="fro")
    print(f"diffrence for matrix {i}:\n {norms[i]}\n")
"""
5. Reflect
If results are not exactly zero:
Suggest reasons why (e.g. numerical errors)
"""
print("rounding errors") 

diffrence for matrix 0:
 [[ 0. -0.  0. -0.]
 [-0.  0. -0.  0.]
 [ 0. -0. -0.  0.]
 [-0.  0. -0.  0.]]

diffrence for matrix 1:
 [[ 0.  0. -0. -0.  0.]
 [ 0. -0.  0. -0. -0.]
 [-0.  0. -0. -0.  0.]
 [-0.  0.  0.  0. -0.]
 [ 0. -0.  0.  0. -0.]]

diffrence for matrix 2:
 [[-0.  0.  0. -0. -0.  0.]
 [ 0. -0. -0.  0.  0. -0.]
 [ 0. -0. -0.  0.  0. -0.]
 [ 0. -0. -0.  0.  0. -0.]
 [-0.  0.  0. -0. -0.  0.]
 [-0.  0.  0. -0. -0.  0.]]

diffrence for matrix 0:
 6.013743634018956e-15

diffrence for matrix 1:
 1.1813714977558165e-14

diffrence for matrix 2:
 4.4803396457306343e-13

rounding errors


# Exercise 4


An interesting property of orthogonal matrices is that 2-norm is 1.
(it is also known as the Induced 2-norm)

This is because all for their singular values and eigen values are 1 (more on these things in a later lecture).

Create a random 13 x 13 matrix and calcuate the 2-norm using both the np.linalg.norm and the manual equation below :

Use: np.linalg.norm(Q,2) - the 2 parameter is important.

This manual formular will be : np.sqrt( np.sum(Q**2) )/np.sqrt(n)

Verify that both calculations give 1 (or very close to 1)

In [23]:
A = np.linalg.qr(np.random.rand(13,13))[0]
print(np.round(np.linalg.norm(A,2),13),"\n")


print(np.round(np.sqrt(np.sum(A**2))/np.sqrt(A.shape[0]),13),"\n")

1.0 

1.0 



# Exercise 5


Part of Exercise 9-7 from the book:
When a matrix A is a tall matrix size M x N (more rows than columns) and full column rank (i.e. rank of A is equal to number of columns), then the first N rows of R after doing QR decompostion is upper triangular and rows N+1..M of R is zero.

Confirm this is the case in python by creating a random (10,4) matrix and inspect if the R matrix obeys this. For this to work you have to use the full-mode decomposition instead of the reduced (default) one.

R is of course not invertible, as it it not square.
But the N x N submatrix of A (the upper-triangular part) is in fact invertible. Verify this in python, by taking first taking the N x N "slice" of this matrix and then calculating the determiant - which should be non-zero to prove it is invertible.
In this case it will be an 4x4 matrix

In [28]:
"""Task

Create a random 10×4 matrix A
"""

M = np.random.randint(0, 10, (10, 4))

print(M, "\n")

"""
Perform QR decomposition (full mode)
"""
Q,R = np.linalg.qr(M, mode="complete")
"""
Check that R:

First 4 rows are upper triangular
"""
print(R,"\n")
"""
Remaining rows are zero

Extract the top 4×4 part of R

Compute its determinant

Confirm determinant is non-zero
"""

[[0 5 2 9]
 [6 1 7 5]
 [9 6 3 8]
 [2 4 3 7]
 [0 8 1 2]
 [3 4 8 4]
 [5 1 1 9]
 [2 5 3 2]
 [1 6 5 5]
 [8 3 1 2]] 

[[-14.96662955  -8.35191381  -8.21828319 -13.22943147]
 [  0.          12.61925258   5.33800292   8.12321712]
 [  0.           0.           8.7158216    2.51439623]
 [  0.           0.           0.         -10.27975185]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]] 



'\nRemaining rows are zero\n\nExtract the top 4×4 part of R\n\nCompute its determinant\n\nConfirm determinant is non-zero\n'