# Lesson 7 - exercises for matrix inverse

# Exercise 1




Create a 2 x 2 matrix and a 3 x 3 matrix.
Make sure they are both invertible - an easy way to do that is to make sure the determinant is not zero.

Test in python that the 3 properties listed on the slide with properties of the inverse holds for both these matrices.

In [9]:
import numpy as np

np.random.seed(42)

while True:
    A2 = np.random.randint(10, size=(2,2))
    if np.linalg.det(A2) != 0:
        break


while True:
    A3 = np.random.randint(10, size=(3,3))
    if np.linalg.det(A3) != 0:
        break
    

print(f"A2 det: {np.linalg.det(A2)}")
print(f"A3 det: {np.linalg.det(A3)}\n")

print(f"A2 rank: {np.linalg.matrix_rank(A2)}")
print(f"A3 rank: {np.linalg.matrix_rank(A3)}\n")

print(f"A2 inverse: \n{np.linalg.inv(A2)}\n")
print(f"A3 inverse: \n{np.linalg.inv(A3)}\n")

print(f"A2*A2^-1 : \n{np.round(np.linalg.inv(A2)@A2, decimals=10)}\n")
print(f"A3*A3^-1 : \n{np.round(np.linalg.inv(A3)@A3, decimals=10)}\n")


A2 det: 2.9999999999999982
A3 det: -102.00000000000004

A2 rank: 2
A3 rank: 3

A2 inverse: 
[[ 1.33333333 -1.        ]
 [-2.33333333  2.        ]]

A3 inverse: 
[[-0.20588235  0.48039216 -0.21568627]
 [ 0.29411765 -0.35294118  0.11764706]
 [-0.20588235  0.14705882  0.11764706]]

A2*A2^-1 : 
[[ 1.  0.]
 [-0.  1.]]

A3*A3^-1 : 
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]



# Exercise 2



Consider the two matrices that you created in exercise 2. \
Are the columns of theses matrices linearly independent? \
How can you test this in python? (hint: several ways)

In [10]:
print("yes they are linear independent, bacause the rand and dimentions are equal")
print(f'A2 rank: {np.linalg.matrix_rank(A2)} And A2 shape: {A2.shape}')
print(f'A3 rank: {np.linalg.matrix_rank(A3)} And A3 shape: {A3.shape}\n\n')

print("and the determinant is not 0, so they are linear independent")



yes they are linear independent, bacause the rand and dimentions are equal
A2 rank: 2 And A2 shape: (2, 2)
A3 rank: 3 And A3 shape: (3, 3)


# Exercise 3

Create a diagonal matrix with values 1,2,3 on the diagonal. \
Why is this matrix invertible? \
Construct the inverse MANUALLY (i.e. not using np.linalg.inv library) and check that it is indeed an inverse.

What happens if you replace the number 3 with 0?
Try it out in python using np.linalg.inv - what happens?

In [16]:
import numpy as np

M = np.array([
    [1,0,0],
    [0,2,0],
    [0,0,3]
])

invM = np.zeros((3,3))

for i in range(len(M)):
    if M[i,i] != 0:
        invM[i,i] = 1 / M[i,i]

print(invM)



M = np.array([
    [1,0,0],
    [0,2,0],
    [0,0,0]
])

invM = np.zeros((3,3))

for i in range(len(M)):
    if M[i,i] != 0:
        invM[i,i] = 1 / M[i,i]

print(invM)
print("it works cause i am good :D")

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0. ]]
it works cause i am good :D


# Exercise 4


The inverse of the inverse is the original matrix as shown in exercises 1 (if the matrix is invertible).
Then the following should also be true:
I.e. $ ((A^{-1})^{-1})^{-1} = A^{-1}  $

Show this is indeed the case in python with an example and compare the left hand side with the right hand side using that norm(left-right) should be close to zero if the two matrices are equal

In [17]:
print(f"norm between A^-1 and ((A^-1)^-1)^-1")
print(np.linalg.norm(np.linalg.inv(A2) - np.linalg.inv(np.linalg.inv(np.linalg.inv(A2)))))
print(np.linalg.norm(np.linalg.inv(A3) - np.linalg.inv(np.linalg.inv(np.linalg.inv(A3)))))

norm between A^-1 and ((A^-1)^-1)^-1
3.1480255910393996e-15
1.576213700060856e-16


# Exercise 5

In this exercise you will use the norm (euclidian distance) to "prove" some properties about inverses. Remember if the norm of the difference between to matrices is zero, or extremely close the zero the two matrices are equal. \
I.e. if np.linalg.norm(X - Y) = 0. \
Construct two square matrices of the same dimensions. Make sure they are invertible.
Then calculate the 3 following matrices (but before calculating, make a guess about which are equal or not) and which are equal or not using the norm as stated above
1. $ (AB)^{-1} $
2. $ A^{-1}B^{-1} $
3. $ B^{-1}A^{-1}  $

\
What can you conclude? (not a proof though!)


In [18]:
import numpy as np

while True:
    A = np.random.randint(10, size=(4,4))
    if np.linalg.det(A) != 0:
        break
    
while True:
    B = np.random.randint(10, size=(4,4))
    if np.linalg.det(A) != 0:
        break
    
AB_inv = np.linalg.inv(A @ B)
A_inv_B_inv = np.linalg.inv(A) @ np.linalg.inv(B)
B_inv_A_inv = np.linalg.inv(B) @ np.linalg.inv(A)

print("i dont think the inverted multoblication is the same as the other")


print(f'AB_inv = A_inv_B_inv: {np.linalg.norm(AB_inv - A_inv_B_inv)}')
print(f'AB_inv = B_inv_A_inv: {np.linalg.norm(AB_inv - B_inv_A_inv)}')
print(f'A_inv_B_inv = B_inv_A_inv: {np.linalg.norm(A_inv_B_inv - B_inv_A_inv)}')



AB_inv = A_inv_B_inv: 0.5337541335650603
AB_inv = B_inv_A_inv: 5.295679187817453e-16
A_inv_B_inv = B_inv_A_inv: 0.5337541335650606


# Exercise 6

The following matrix is not a square matrix, so it does not have a full inverse. However, it does have a left inverse.
Construct the left inverse and test it is indeed a left inverse.

In [17]:
import numpy as np

T = np.array([ [1,0],[2,1],[3,2]])
print(T)
print("")

print("T.T @ T: \n", T.T @ T)

left_inverse = np.linalg.inv(T.T@T)@T.T
print(left_inverse)
print("")
print(f"left inverse * T: \n{np.round(left_inverse@T,8)}\n")


[[1 0]
 [2 1]
 [3 2]]

T.T @ T: 
 [[14  8]
 [ 8  5]]
[[ 0.83333333  0.33333333 -0.16666667]
 [-1.33333333 -0.33333333  0.66666667]]

left inverse * T: 
[[ 1. -0.]
 [ 0.  1.]]



# Exercise 7 (optional)

Derive the right-invefrse (not left!) from wide matrices by following the same method that derives the left inverse (and adjusting along as neccesary)

In [36]:
import numpy as np

T = np.array([ [1,0],[2,1],[3,2]]).T
print(T)
print("")

print("T.T @ T: \n", T.T @ T)

right_inverse = T.T@np.linalg.inv(T@T.T)
print(right_inverse)
print("")
print(f"T * right inverse: \n{np.round(T@right_inverse,10)}\n")

[[1 2 3]
 [0 1 2]]

T.T @ T: 
 [[ 1  2  3]
 [ 2  5  8]
 [ 3  8 13]]
[[ 0.83333333 -1.33333333]
 [ 0.33333333 -0.33333333]
 [-0.16666667  0.66666667]]

T * right inverse: 
[[ 1.  0.]
 [-0.  1.]]

